name: EnvNoBug
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=21.1.0=py38h497a2fe_0
  - async_generator=1.10=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - ca-certificates=2021.10.8=ha878542_0
  - cffi=1.14.0=py38h2e261b9_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - debugpy=1.4.1=py38h709712a_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h9c3ff4c_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=hf34092f_1004
  - glib=2.58.3=py38h73cb85d_1004
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - icu=67.1=he1b5a44_0
  - importlib-metadata=4.8.1=py38h578d9bd_0
  - ipykernel=6.4.2=py38he5a9106_0
  - ipython=7.28.0=py38he5a9106_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py38h578d9bd_2
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=4.1.2=pyhd8ed1ab_0
  - jupyter=1.0.0=py38h578d9bd_6
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=pyhd8ed1ab_2
  - jupyter_core=4.8.1=py38h578d9bd_0
  - jupyter_highlight_selected_word=0.2.0=py38h578d9bd_1002
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.4.1=py38h578d9bd_2
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - kiwisolver=1.3.2=py38h1fd1430_0
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_openblas
  - libcblas=3.9.0=12_linux64_openblas
  - libclang=10.0.1=default_hde54327_1
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.10=h9b69904_4
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - libpq=12.3=h255efa7_3
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=h6f004c6_2
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=h68273f3_2
  - libxslt=1.1.33=hf705e74_1
  - libzlib=1.2.11=h36c2ea0_1013
  - lxml=4.6.3=py38hf1fe3a4_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib=3.4.3=py38h578d9bd_1
  - matplotlib-base=3.4.3=py38hf4fb855_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38h497a2fe_1004
  - mysql-common=8.0.26=ha770c72_0
  - mysql-libs=8.0.26=hfa10184_0
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=5.6.1=pyhd8ed1ab_2
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.4.5=pyha770c72_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - pandas=1.3.4=py38h43a58ef_0
  - pandoc=2.14.2=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.2=py38h8e6f84c_0
  - pip=21.3=pyhd8ed1ab_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - prompt_toolkit=3.0.20=hd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pyrsistent=0.17.3=py38h497a2fe_2
  - python=3.8.0=h357f687_5
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd8ed1ab_0
  - pyyaml=6.0=py38h497a2fe_0
  - pyzmq=22.3.0=py38h2035c66_0
  - qt=5.12.9=h1f2b2cb_0
  - qtconsole=5.1.1=pyhd8ed1ab_0
  - qtpy=1.11.2=pyhd8ed1ab_0
  - readline=8.1=h46c0cb4_0
  - scikit-learn=1.0=py38hacb3eff_1
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.2.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h9cd32fc_2
  - statsmodels=0.13.0=py38h6c62de6_0
  - terminado=0.12.1=py38h578d9bd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=h27826a3_1
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.0=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - antlerinator==4.7.1.post1
    - antlr4-python3-runtime==4.7.1
    - astpretty==2.1.0
    - attrs==20.3.0
    - autopep8==1.5.7
    - blis==0.7.5
    - catalogue==2.0.6
    - certifi==2021.5.30
    - charset-normalizer==2.0.7
    - cirq==0.13.1
    - cirq-aqt==0.13.1
    - cirq-core==0.13.1
    - cirq-google==0.13.1
    - cirq-ionq==0.13.1
    - cirq-pasqal==0.13.1
    - cirq-rigetti==0.13.1
    - cirq-web==0.13.1
    - click==8.0.3
    - coverage==6.3.2
    - cryptography==35.0.0
    - cupy-cuda112==9.6.0
    - cupy-cuda91==7.8.0
    - cupy-cuda92==9.6.0
    - cymem==2.0.6
    - deap==1.3.1
    - deprecated==1.2.13
    - deprecation==2.1.0
    - dill==0.3.4
    - dlx==1.0.4
    - docplex==2.22.213
    - duet==0.2.3
    - fastdtw==0.3.4
    - fastjsonschema==2.15.1
    - fastrlock==0.8
    - filelock==3.4.2
    - grammarinator==19.3
    - grpcio==1.41.0
    - h11==0.9.0
    - h5py==3.2.1
    - httpcore==0.11.1
    - httpx==0.15.5
    - huggingface-hub==0.4.0
    - idna==2.10
    - immutables==0.6
    - inators==2.1.0
    - iso8601==0.1.16
    - jinja2==2.11.0
    - jupyter-client==6.1.12
    - langcodes==3.3.0
    - lark==0.11.3
    - lark-parser==0.12.0
    - llvmlite==0.37.0
    - more-itertools==8.10.0
    - mpmath==1.2.1
    - msgpack==0.6.2
    - multitasking==0.0.9
    - murmurhash==1.0.6
    - networkx==2.7.1
    - nltk==3.6.5
    - ntlm-auth==1.5.0
    - numba==0.54.1
    - numpy==1.20.0
    - openfermion==1.3.0
    - packaging==21.3
    - pathy==0.6.1
    - pbr==5.8.0
    - peewee==3.14.8
    - ply==3.11
    - preshed==3.0.6
    - psutil==5.8.0
    - pubchempy==1.0.4
    - pycodestyle==2.8.0
    - pydot==1.4.2
    - pyjwt==1.7.1
    - pylatexenc==2.10
    - pyquil==3.0.1
    - python-afl==0.7.3
    - python-constraint==1.4.0
    - graphviz==0.14
    - python-rapidjson==1.5
    - pytket==0.18.0
    - pytket-cirq==0.19.0
    - pytket-qiskit==0.21.0
    - qcs-api-client==0.8.0
    - qiskit==0.33.1
    - qiskit-aer==0.9.1
    - qiskit-aer-gpu==0.9.1
    - qiskit-aqua==0.9.5
    - qiskit-ibmq-provider==0.18.2
    - qiskit-ignis==0.7.0
    - qiskit-terra==0.19.1
    - quandl==3.6.1
    - regex==2021.11.10
    - requests==2.26.0
    - requests-ntlm==1.1.0
    - retry==0.9.2
    - retrying==1.3.3
    - retworkx==0.10.2
    - rfc3339==6.2
    - rfc3986==1.5.0
    - rpcq==3.9.2
    - ruamel-yaml==0.17.17
    - ruamel-yaml-clib==0.2.6
    - sacremoses==0.0.47
    - scipy==1.7.3
    - smart-open==5.2.1
    - snakeviz==2.1.1
    - sortedcontainers==2.4.0
    - spacy==3.2.1
    - spacy-alignments==0.8.4
    - spacy-loggers==1.0.1
    - spacy-transformers==1.1.4
    - srsly==2.4.2
    - stevedore==3.5.0
    - symengine==0.8.1
    - sympy==1.10
    - thinc==8.0.13
    - tokenizers==0.10.3
    - torch==1.10.0
    - transformers==4.15.0
    - tweedledum==1.1.1
    - typer==0.4.0
    - types-jinja2==2.11.9
    - types-markupsafe==1.1.10
    - types-pkg-resources==0.1.3
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - wasabi==0.9.0
    - websocket-client==1.2.1
    - werkzeug==2.0.2
    - wrapt==1.13.3
    - yfinance==0.1.64
    - z3-solver==4.8.14.0